// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth": {
    params: {};
  };
  "/upload": {
    params: {};
  };
  "/cv/:id": {
    params: {
      "id": string;
    };
  };
  "/dashboard": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth" | "/upload" | "/cv/:id" | "/dashboard";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/auth.tsx": {
    id: "routes/auth";
    page: "/auth";
  };
  "routes/upload.tsx": {
    id: "routes/upload";
    page: "/upload";
  };
  "routes/cv.tsx": {
    id: "routes/cv";
    page: "/cv/:id";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/auth": typeof import("./app/routes/auth.tsx");
  "routes/upload": typeof import("./app/routes/upload.tsx");
  "routes/cv": typeof import("./app/routes/cv.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
};